name: <your_conda_env_name>
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=12.1
  - pip:
    # --- 核心深度学习 ---
    - torch==2.5.1
    - torchvision==0.20.1
    - tensorboard==2.20.0
    
    # --- 机器人与仿真 ---
    - mujoco==3.4.0
    - nvidia-curobo==0.7.7.post1.dev5
    - warp-lang==1.11.0
    
    # --- 数学与几何 ---
    - numpy==2.2.6
    - scipy==1.15.3
    - pyquaternion==0.9.9
    - trimesh==4.11.1
    - open3d==0.19.0
    - opencv-python==4.13.0.90
    - shapely==2.1.2
    
    # --- 工具与可视化 ---
    - tqdm==4.67.1
    - pyyaml==6.0.3
    - matplotlib==3.10.8
    - pandas==2.3.3
    - jupyterlab-widgets
    - ipywidgets
    
    # --- 依赖项
    - urchin==0.0.30
    - yourdfpy==0.0.59
    - manifold3d
    - gymnasium==1.2.3